export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS'
}
export const userConstants ={
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST ',
    USER_REGISTER_SUCCESS  : 'USER_REGISTER_SUCCESS ',
    USER_REGISTER_FAILURE  : 'USER_REGISTER_FAILURE '
}
export const categoryConstants ={
    GET_ALL_CATEGORY_REQUEST : ' GET_ALL_CATEGORY_REQUEST ',
    GET_ALL_CATEGORY_SUCCESS : ' GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE : ' GET_ALL_CATEGORY_FAILURE'
}